POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QgTWN0ZXN0MTIzNDUiLCJpZCI6IjYzODY3NjUxYjYxZGFkN2VlZTg3Yjk5MyIsImlhdCI6MTY2OTgwOTkwMn0.0CWG7u_O-Q-BuNyzzRk_8P_Clma1hmGoVmOE585TDFw

{
    "title": "Test",
    "author": "Test Mctest",
    "url": "www.test.fi",
    "likes": "3"

}

###

DELETE http://localhost:3003/api/blogs/63867a540f8011c080fd681e
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QgTWN0ZXN0MTIzNDUiLCJpZCI6IjYzODY3NjUxYjYxZGFkN2VlZTg3Yjk5MyIsImlhdCI6MTY2OTgwOTkwMn0.0CWG7u_O-Q-BuNyzzRk_8P_Clma1hmGoVmOE585TDFw

###

GET http://localhost:3003/api/blogs