POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QgTWN0ZXN0MTIzNDUiLCJpZCI6IjYzODY3NjUxYjYxZGFkN2VlZTg3Yjk5MyIsImlhdCI6MTY2OTc1NjUxN30.pHOcFn6TLNZFPo926N2uNIzuv65hjDkIcx1-AzLQ-mw

{
    "title": "Test",
    "author": "Test Mctest",
    "url": "www.test.fi",
    "likes": "3"

}

###

DELETE http://localhost:3003/api/blogs/63867a540f8011c080fd681e
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QgTWN0ZXN0MTIzNDUiLCJpZCI6IjYzODY3NjUxYjYxZGFkN2VlZTg3Yjk5MyIsImlhdCI6MTY2OTc1NjUxN30.pHOcFn6TLNZFPo926N2uNIzuv65hjDkIcx1-AzLQ-mw

###

GET http://localhost:3003/api/blogs